services:
  postgres:
    image: postgres:16
    container_name: datadock-postgres

    environment:
      POSTGRES_USER: datadock
      POSTGRES_PASSWORD: datadock_password
      POSTGRES_DB: datadock

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: